// SPDX-License-Identifier: GPL-3.0-or-later
// Guest CPU state and helpers used by recompiled code (generated by bbrecomp). Every guest function becomes
// `void f_<vaddr>(bb::rt::Context&)`; the guest ABI (SysV, stack layout, return addresses) is kept inside Context,
// so the host calling convention (Windows x64 or SysV) never matters for game code.
#pragma once
#include <atomic>
#include <bit>
#include <immintrin.h>
#include <cstdint>
#include <vector>
#include <cstring>
#include <limits>
#include <cmath>
#include <type_traits>
#if defined(_MSC_VER)
#include <intrin.h>  // _mul128/_umul128/_udiv128/_div128, __rdtsc
#else
#include <x86intrin.h>  // __rdtsc
#endif

// Hot helpers are called for almost every guest instruction; giant generated functions exhaust the compiler's inline
// budget, which left them as calls (several % of frame time). Force them inline.
#if defined(_MSC_VER)
#define BB_INLINE __forceinline
#else
#define BB_INLINE inline __attribute__((always_inline))
#endif

namespace bb::rt {

struct Context {
    uint64_t r[16] = {};  // rax rcx rdx rbx rsp rbp rsi rdi r8..r15 (x86 encoding order)
    bool cf = false, pf = false, zf = false, sf = false, of = false, df = false;
    uint8_t ymm[16][32] = {};  // accessed via memcpy / unaligned loads; no alignas (avoids padding warnings)
    uint64_t fs_base = 0;
    // Host address of guest address 0. With identity mapping (guest memory reserved at its own addresses, as
    // planned for the game) this is 0; tests use a heap buffer. Integer, not pointer: no null-pointer arithmetic.
    uintptr_t base = 0;
    // x87: physical registers (host doubles, see "x87" below), top-of-stack, status condition bits (C0 0x100,
    // C1 0x200, C2 0x400, C3 0x4000) and control word. MMX registers are kept separately (no x87 aliasing).
    double fpu[8] = {};
    uint8_t ftop = 0;
    uint16_t fsw = 0;
    uint16_t fcw = 0x37F;
    uint64_t mm[8] = {};
};

using GuestFn = void (*)(Context&);

// The Context of the guest thread running on this host thread (set by the thread's entry code; used by crash
// reports to print guest registers and a guest backtrace).
extern thread_local Context* current_context;
// Optional call history (compile the recompiled code with -DBB_TRACE_CALLS): ring of the last function entries per
// thread, printed by crash reports. Costs a thread-local store per call, so it is off by default.
struct TraceRing {
    uint64_t entries[64];
    uint32_t next;
};
extern thread_local TraceRing trace_ring;
extern uint64_t trace_fn;  // BB_TRACE_FN=<hex vaddr>: log arguments on entry and rax on exit of that function
void trace_fn_report(const Context& c, uint64_t addr, bool entry);
struct TraceGuard {
    const Context& c;
    uint64_t addr;
    TraceGuard(const Context& ctx, uint64_t a) : c(ctx), addr(a) {
        trace_ring.entries[trace_ring.next++ & 63] = a;
        if (a == trace_fn) trace_fn_report(c, a, true);
    }
    ~TraceGuard() {
        if (addr == trace_fn) trace_fn_report(c, addr, false);
    }
};
#ifdef BB_TRACE_CALLS
#define BB_TRACE_ENTER(a) ::bb::rt::TraceGuard bb_trace_guard_(c, (a))
#else
#define BB_TRACE_ENTER(a) ((void)0)
#endif

// Debug view of a guest thread (for hang/crash reports from other threads).
struct ThreadDebug {
    const char* name;
    Context* const* context;
    const TraceRing* ring;
    const struct ImportEntry* const* last_import;
    uint64_t os_thread_id;  // host thread id (0 = unknown), lets the watchdog sample the host RIP
};
void register_debug_thread(const char* name, uint64_t os_thread_id = 0);  // registers the calling thread's thread_locals
const std::vector<ThreadDebug>& debug_threads();

struct ImportEntry;
extern thread_local const ImportEntry* last_import;  // most recent HLE import called on this thread (crash reports)
struct FunctionEntry {
    uint64_t addr;  // runtime guest address (vaddr + kLoadBias)
    GuestFn fn;
};

// Provided by the generated translation unit: all recompiled functions sorted by runtime address, and the load bias
// the code was generated for (guest address = vaddr + kLoadBias; load_image must use the same value).
extern const FunctionEntry kFunctions[];
extern const size_t kFunctionCount;
extern const uint64_t kLoadBias;

// Imports. The loader writes kImportBase + symbol_index * 16 into every symbol relocation slot (GOT); these addresses
// are never mapped. call_indirect recognises them (and the PLT entries listed in kImports) and dispatches to HLE.
inline constexpr uint64_t kImportBase = 0x7F0000000000ull;
inline constexpr uint64_t kImportStride = 16;
inline constexpr uint64_t kExitAddress = 0x7EFFFFFFF000ull;  // passed to the entry point as the exit function
struct ImportEntry {
    uint32_t symbol;      // index in the dynamic symbol table
    uint64_t plt;         // runtime address of its PLT entry, 0 if none
    const char* nid;
    const char* library;
    const char* name;     // resolved name or "" (bbrecomp --names)
};
extern const ImportEntry kImports[];  // sorted by symbol
extern const size_t kImportCount;

// HLE registry (runtime/hle_registry.cpp): host implementation for an import NID, or nullptr.
GuestFn find_hle(const char* nid);
void register_hle(const char* nid, GuestFn fn);

// Runtime services (guest.cpp). Indirect control flow resolves through kFunctions, then imports.
[[noreturn]] void unsupported(Context& c, uint64_t ip, const char* mnemonic);
void call_indirect(Context& c, uint64_t target);  // return address already pushed by the caller
GuestFn lookup(uint64_t addr);
const ImportEntry* find_import(uint64_t target);  // by synthetic address or PLT entry; nullptr otherwise

BB_INLINE uint8_t* host(const Context& c, uint64_t a) { return reinterpret_cast<uint8_t*>(c.base + a); }

// Debug (BB_TRACE_CALLS builds): a guest access below 64 KiB (null object + field offset) is reported with the
// recent function entries instead of faulting inside the memcpy.
[[noreturn]] void bad_access(Context& c, uint64_t addr, size_t size, bool write);
#ifdef BB_TRACE_CALLS
#define BB_CHECK_ACCESS(c, a, n, w) ((c).base == 0 && (a) < 0x10000 ? bad_access(c, a, n, w) : (void)0)
#else
#define BB_CHECK_ACCESS(c, a, n, w) ((void)0)
#endif
template <typename T>
BB_INLINE T ld(Context& c, uint64_t a) {
    BB_CHECK_ACCESS(c, a, sizeof(T), false);
    T v;
    std::memcpy(&v, host(c, a), sizeof v);
    return v;
}
// Debug watchpoint (BB_TRACE_CALLS builds): BB_WATCH=<hex address> reports every guest store that covers it.
extern uint64_t watch_addr;
void watch_hit(Context& c, uint64_t addr, size_t size, uint64_t value);
extern uint64_t watch_value;  // BB_WATCH_VALUE=<hex>: report every 8-byte guest store of exactly this value (trace builds)
#ifdef BB_TRACE_CALLS
#define BB_WATCH_RANGE(c, a, n) (((a) <= watch_addr && watch_addr < (a) + (n)) ? watch_hit(c, a, n, 0) : (void)0)
#else
#define BB_WATCH_RANGE(c, a, n) ((void)0)
#endif
template <typename T>
BB_INLINE void st(Context& c, uint64_t a, T v) {
    BB_CHECK_ACCESS(c, a, sizeof v, true);
#ifdef BB_TRACE_CALLS
    if (a <= watch_addr && watch_addr < a + sizeof v) watch_hit(c, a, sizeof v, uint64_t(v));
    if (sizeof v == 8 && watch_value != ~0ull && uint64_t(v) == watch_value) watch_hit(c, a, sizeof v, uint64_t(v));
#endif
    std::memcpy(host(c, a), &v, sizeof v);
}

// RFLAGS image of the modelled flags (bit 1 is always set; AF is not modelled).
BB_INLINE uint64_t rflags(const Context& c) {
    return 2 | uint64_t(c.cf) | uint64_t(c.pf) << 2 | uint64_t(c.zf) << 6 | uint64_t(c.sf) << 7 |
           uint64_t(c.df) << 10 | uint64_t(c.of) << 11;
}
// setjmp/longjmp: generated code calls setjmp_save inline (the guest jmp_buf holds rbx, rbp, r12-r15, rsp, resume address);
// the HLE longjmp restores those registers and throws LongJmp, which the function that "called setjmp" catches.
struct LongJmp {
    uint64_t ret_addr;
};
inline void setjmp_save(Context& c, uint64_t jb, uint64_t ret_addr) {
    static constexpr int kRegs[7] = {3, 5, 12, 13, 14, 15, 4};  // rbx rbp r12 r13 r14 r15 rsp
    for (int i = 0; i < 7; ++i) st<uint64_t>(c, jb + 8 * i, c.r[kRegs[i]]);
    st<uint64_t>(c, jb + 56, ret_addr);
}
[[noreturn]] inline void longjmp_restore(Context& c, uint64_t jb, uint64_t val) {
    static constexpr int kRegs[7] = {3, 5, 12, 13, 14, 15, 4};
    for (int i = 0; i < 7; ++i) c.r[kRegs[i]] = ld<uint64_t>(c, jb + 8 * i);
    c.r[0] = uint32_t(val) ? uint32_t(val) : 1;
    throw LongJmp{ld<uint64_t>(c, jb + 56)};
}
BB_INLINE void set_rflags(Context& c, uint64_t f) {
    c.cf = f & 1;
    c.pf = f >> 2 & 1;
    c.zf = f >> 6 & 1;
    c.sf = f >> 7 & 1;
    c.df = f >> 10 & 1;
    c.of = f >> 11 & 1;
}

template <typename T>
BB_INLINE bool sign(T v) {
    return std::make_signed_t<T>(v) < 0;
}
template <typename T>
BB_INLINE void szp(Context& c, T r) {
    c.zf = r == 0;
    c.sf = sign(r);
#if defined(_MSC_VER)  // std::popcount is a call chain that stays out of line in giant functions
    c.pf = (__popcnt16(uint8_t(r)) & 1) == 0;
#else
    c.pf = !__builtin_parity(uint8_t(r));
#endif
}
template <typename T>
BB_INLINE T f_add(Context& c, T a, T b) {
    T r = T(a + b);
    c.cf = r < a;
    c.of = sign(T((a ^ r) & (b ^ r)));
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_sub(Context& c, T a, T b) {
    T r = T(a - b);
    c.cf = a < b;
    c.of = sign(T((a ^ b) & (a ^ r)));
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_logic(Context& c, T r) {
    c.cf = c.of = false;
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_inc(Context& c, T a) {  // CF preserved
    bool cf = c.cf;
    T r = f_add(c, a, T(1));
    c.cf = cf;
    return r;
}
template <typename T>
BB_INLINE T f_dec(Context& c, T a) {
    bool cf = c.cf;
    T r = f_sub(c, a, T(1));
    c.cf = cf;
    return r;
}
template <typename T>
BB_INLINE T f_neg(Context& c, T a) {
    T r = f_sub(c, T(0), a);
    c.cf = a != 0;
    return r;
}
// Shifts: count already masked by the caller (& 31 / & 63); count 0 leaves flags untouched.
template <typename T>
BB_INLINE T f_shl(Context& c, T a, unsigned n) {
    if (!n) return a;
    T r = T(a << n);
    c.cf = (a >> (sizeof(T) * 8 - n)) & 1;
    c.of = sign(r) != c.cf;
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_shr(Context& c, T a, unsigned n) {
    if (!n) return a;
    T r = T(a >> n);
    c.cf = (a >> (n - 1)) & 1;
    c.of = sign(a);
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_sar(Context& c, T a, unsigned n) {
    if (!n) return a;
    using S = std::make_signed_t<T>;
    T r = T(S(a) >> n);
    c.cf = (S(a) >> (n - 1)) & 1;
    c.of = false;
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_imul(Context& c, T a, T b) {  // truncating signed multiply; CF=OF=overflow
    using S = std::make_signed_t<T>;
    S r;
    bool ovf;
    if constexpr (sizeof(T) == 8) {
#if defined(_MSC_VER) && !defined(__clang__)
        int64_t hi;
        r = _mul128(S(a), S(b), &hi);
        ovf = hi != (r < 0 ? -1 : 0);
#else
        __int128 w = (__int128)S(a) * S(b);
        r = S(w);
        ovf = w != r;
#endif
    } else {
        int64_t w = int64_t(S(a)) * int64_t(S(b));
        r = S(w);
        ovf = w != r;
    }
    c.cf = c.of = ovf;
    szp(c, T(r));
    return T(r);
}
template <typename T>
BB_INLINE T f_adc(Context& c, T a, T b) {
    const bool cin = c.cf;
    T r = T(a + b + T(cin));
    c.cf = cin ? r <= a : r < a;
    c.of = sign(T((a ^ r) & (b ^ r)));
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_sbb(Context& c, T a, T b) {
    const bool cin = c.cf;
    T r = T(a - b - T(cin));
    c.cf = cin ? a <= b : a < b;
    c.of = sign(T((a ^ b) & (a ^ r)));
    szp(c, r);
    return r;
}
// Rotates: n is the count already masked to 5/6 bits; 0 leaves flags untouched. OF is defined only for n == 1.
template <typename T>
BB_INLINE T f_rol(Context& c, T a, unsigned n) {
    if (!n) return a;
    constexpr unsigned B = sizeof(T) * 8;
    const unsigned m = n % B;
    T r = m ? T((a << m) | (a >> (B - m))) : a;
    c.cf = r & 1;
    if (n == 1) c.of = sign(r) != c.cf;
    return r;
}
template <typename T>
BB_INLINE T f_ror(Context& c, T a, unsigned n) {
    if (!n) return a;
    constexpr unsigned B = sizeof(T) * 8;
    const unsigned m = n % B;
    T r = m ? T((a >> m) | (a << (B - m))) : a;
    c.cf = sign(r);
    if (n == 1) c.of = sign(r) != sign(T(r << 1));
    return r;
}

// One-operand mul/imul: full-width product as {low, high}; CF=OF = high part is significant.
template <typename T>
BB_INLINE T f_mul_wide(Context& c, T a, T b, T& hi) {
    if constexpr (sizeof(T) == 8) {
#if defined(_MSC_VER) && !defined(__clang__)
        uint64_t h;
        uint64_t lo = _umul128(a, b, &h);
        hi = h;
#else
        unsigned __int128 w = (unsigned __int128)a * b;
        uint64_t lo = uint64_t(w);
        hi = uint64_t(w >> 64);
#endif
        c.cf = c.of = hi != 0;
        return lo;
    } else {
        uint64_t w = uint64_t(a) * uint64_t(b);
        hi = T(w >> (sizeof(T) * 8));
        c.cf = c.of = hi != 0;
        return T(w);
    }
}
template <typename T>
BB_INLINE T f_imul_wide(Context& c, T a, T b, T& hi) {
    using S = std::make_signed_t<T>;
    if constexpr (sizeof(T) == 8) {
#if defined(_MSC_VER) && !defined(__clang__)
        int64_t h;
        int64_t lo = _mul128(S(a), S(b), &h);
        hi = T(h);
#else
        __int128 w = (__int128)S(a) * S(b);
        int64_t lo = int64_t(w);
        hi = T(uint64_t(w >> 64));
#endif
        c.cf = c.of = S(hi) != (lo < 0 ? -1 : 0);
        return T(lo);
    } else {
        int64_t w = int64_t(S(a)) * int64_t(S(b));
        hi = T(uint64_t(w) >> (sizeof(T) * 8));
        c.cf = c.of = w != int64_t(S(T(w)));
        return T(w);
    }
}

// div/idiv: (hi:lo) / d. #DE (zero divisor or quotient overflow) is a guest crash: report like a trap.
[[noreturn]] void divide_error(Context& c);
template <typename T>
BB_INLINE void f_div(Context& c, T hi, T lo, T d, T& q, T& r) {
    if (d == 0 || hi >= d) divide_error(c);
    if constexpr (sizeof(T) == 8) {
#if defined(_MSC_VER) && !defined(__clang__)
        uint64_t rem;
        q = _udiv128(hi, lo, d, &rem);
        r = rem;
#else
        unsigned __int128 n = ((unsigned __int128)hi << 64) | lo;
        q = uint64_t(n / d);
        r = uint64_t(n % d);
#endif
    } else {
        uint64_t n = (uint64_t(hi) << (sizeof(T) * 8)) | lo;
        q = T(n / d);
        r = T(n % d);
    }
}
template <typename T>
BB_INLINE void f_idiv(Context& c, T hi, T lo, T d, T& q, T& r) {
    using S = std::make_signed_t<T>;
    if (d == 0) divide_error(c);
    if constexpr (sizeof(T) == 8) {
#if defined(_MSC_VER) && !defined(__clang__)
        int64_t rem;
        int64_t qq = _div128(int64_t(hi), int64_t(lo), int64_t(d), &rem);  // raises #DE itself on overflow
        q = T(qq);
        r = T(rem);
#else
        __int128 n = (__int128)(((unsigned __int128)hi << 64) | lo);
        __int128 qq = n / S(d);
        if (qq > INT64_MAX || qq < INT64_MIN) divide_error(c);
        q = T(uint64_t(qq));
        r = T(uint64_t(n % S(d)));
#endif
    } else {
        int64_t n = int64_t((uint64_t(hi) << (sizeof(T) * 8)) | lo);
        int64_t qq = n / S(d);
        if (qq > (std::numeric_limits<S>::max)() || qq < (std::numeric_limits<S>::min)()) divide_error(c);
        q = T(qq);
        r = T(n % S(d));
    }
}

template <typename T>
inline T bswap(T v) {
    T r = 0;
    for (size_t i = 0; i < sizeof(T); ++i) r = T((r << 8) | ((v >> (8 * i)) & 0xFF));
    return r;
}
// lzcnt/tzcnt: CF = source was zero, ZF = result is zero. popcnt: ZF = source was zero, other flags cleared.
template <typename T>
BB_INLINE T f_lzcnt(Context& c, T a) {
    T r = T(std::countl_zero(a));
    c.cf = a == 0;
    c.zf = r == 0;
    return r;
}
template <typename T>
BB_INLINE T f_tzcnt(Context& c, T a) {
    T r = T(std::countr_zero(a));
    c.cf = a == 0;
    c.zf = r == 0;
    return r;
}
template <typename T>
BB_INLINE T f_popcnt(Context& c, T a) {
    c.cf = c.of = c.sf = c.pf = false;
    c.zf = a == 0;
    return T(std::popcount(a));
}
// BMI1 bextr: start = ctl[7:0], length = ctl[15:8]; ZF from result, CF = OF = 0.
template <typename T>
BB_INLINE T f_bextr(Context& c, T src, T ctl) {
    constexpr unsigned B = sizeof(T) * 8;
    const unsigned start = unsigned(ctl & 0xFF), len = unsigned((ctl >> 8) & 0xFF);
    T r = start >= B ? T(0) : T(src >> start);
    if (len < B) r &= T((T(1) << len) - 1);
    c.cf = c.of = false;
    c.zf = r == 0;
    return r;
}
// BMI1 blsi/blsr/blsmsk: ZF/SF from result, CF as documented, OF = 0 (PF is architecturally undefined).
template <typename T>
BB_INLINE T f_blsi(Context& c, T s) {
    T r = T(s & T(T(0) - s));
    c.cf = s != 0;
    c.of = false;
    c.zf = r == 0;
    c.sf = sign(r);
    return r;
}
template <typename T>
BB_INLINE T f_blsr(Context& c, T s) {
    T r = T(s & T(s - 1));
    c.cf = s == 0;
    c.of = false;
    c.zf = r == 0;
    c.sf = sign(r);
    return r;
}
template <typename T>
BB_INLINE T f_blsmsk(Context& c, T s) {
    T r = T(s ^ T(s - 1));
    c.cf = s == 0;
    c.of = c.zf = false;
    c.sf = sign(r);
    return r;
}
// Rotate through carry; the (already 5/6-bit masked) count wraps modulo width+1. OF is defined for count 1 only.
template <typename T>
inline T f_rcl(Context& c, T a, unsigned n) {
    constexpr unsigned B = sizeof(T) * 8;
    n %= B + 1;
    if (!n) return a;
    for (unsigned i = 0; i < n; ++i) {
        const bool top = sign(a);
        a = T(T(a << 1) | T(c.cf));
        c.cf = top;
    }
    c.of = sign(a) != c.cf;
    return a;
}
template <typename T>
inline T f_rcr(Context& c, T a, unsigned n) {
    constexpr unsigned B = sizeof(T) * 8;
    n %= B + 1;
    if (!n) return a;
    for (unsigned i = 0; i < n; ++i) {
        const bool low = a & 1;
        a = T(T(a >> 1) | T(T(c.cf) << (B - 1)));
        c.cf = low;
    }
    c.of = sign(a) != sign(T(a << 1));
    return a;
}
// Double-precision shifts. ponytail: 16-bit counts >= 16 are architecturally undefined; they wrap modulo the width.
template <typename T>
BB_INLINE T f_shld(Context& c, T d, T s, unsigned n) {
    constexpr unsigned B = sizeof(T) * 8;
    n %= B;
    if (!n) return d;
    T r = T(T(d << n) | T(s >> (B - n)));
    c.cf = (d >> (B - n)) & 1;
    c.of = sign(r) != sign(d);
    szp(c, r);
    return r;
}
template <typename T>
BB_INLINE T f_shrd(Context& c, T d, T s, unsigned n) {
    constexpr unsigned B = sizeof(T) * 8;
    n %= B;
    if (!n) return d;
    T r = T(T(d >> n) | T(s << (B - n)));
    c.cf = (d >> (n - 1)) & 1;
    c.of = sign(r) != sign(d);
    szp(c, r);
    return r;
}
// cpuid: a fixed AMD Jaguar-like (PS4) identity instead of the host's; unknown leaves return zeros.
inline void cpuid(Context& c) {
    uint32_t a = 0, b = 0, cx = 0, d = 0;
    switch (uint32_t(c.r[0])) {
    case 0: a = 0xD; b = 0x68747541; cx = 0x444D4163; d = 0x69746E65; break;  // "AuthenticAMD"
    case 1: a = 0x00740F00; b = 0x00020800; cx = 0x3ED8220B; d = 0x178BFBFF; break;
    case 7: b = 0x8; break;  // BMI1
    case 0x80000000u: a = 0x80000008u; break;
    case 0x80000001u: a = 0x00740F00; cx = 0x3E3; d = 0x2A500800; break;
    default: break;
    }
    c.r[0] = a;
    c.r[3] = b;
    c.r[1] = cx;
    c.r[2] = d;
}
// String instructions: `rep` is 0 (none), 1 (rep/repe) or 2 (repne); element type T; direction from DF.
// Exact guest semantics: rcx/rsi/rdi updated per element, flags only for cmps/scas.
template <typename T>
inline void str_movs(Context& c, int rep) {
    const uint64_t step = c.df ? uint64_t(0) - sizeof(T) : sizeof(T);
    if (rep && !c.df && c.r[1]) {  // forward, non-overlapping: one memcpy
        const uint64_t len = c.r[1] * sizeof(T);
        const uintptr_t s = uintptr_t(host(c, c.r[6])), d = uintptr_t(host(c, c.r[7]));
        if (d >= s + len || d + len <= s) {
            BB_WATCH_RANGE(c, c.r[7], len);
            std::memcpy(host(c, c.r[7]), host(c, c.r[6]), len);
            c.r[6] += len;
            c.r[7] += len;
            c.r[1] = 0;
            return;
        }
    }
    while (!rep || c.r[1]) {
        st<T>(c, c.r[7], ld<T>(c, c.r[6]));
        c.r[6] += step;
        c.r[7] += step;
        if (!rep) return;
        --c.r[1];
    }
}
template <typename T>
inline void str_stos(Context& c, int rep, T v) {
    const uint64_t step = c.df ? uint64_t(0) - sizeof(T) : sizeof(T);
    while (!rep || c.r[1]) {
        st<T>(c, c.r[7], v);
        c.r[7] += step;
        if (!rep) return;
        --c.r[1];
    }
}
// Returns false if rep with rcx == 0 (nothing loaded); otherwise `v` is the last loaded element.
template <typename T>
inline bool str_lods(Context& c, int rep, T& v) {
    const uint64_t step = c.df ? uint64_t(0) - sizeof(T) : sizeof(T);
    bool ran = false;
    while (!rep || c.r[1]) {
        v = ld<T>(c, c.r[6]);
        c.r[6] += step;
        ran = true;
        if (!rep) break;
        --c.r[1];
    }
    return ran;
}
template <typename T>
inline void str_cmps(Context& c, int rep) {
    const uint64_t step = c.df ? uint64_t(0) - sizeof(T) : sizeof(T);
    while (!rep || c.r[1]) {
        f_sub<T>(c, ld<T>(c, c.r[6]), ld<T>(c, c.r[7]));
        c.r[6] += step;
        c.r[7] += step;
        if (!rep) return;
        --c.r[1];
        if (rep == 1 ? !c.zf : c.zf) return;
    }
}
template <typename T>
inline void str_scas(Context& c, int rep, T acc) {
    const uint64_t step = c.df ? uint64_t(0) - sizeof(T) : sizeof(T);
    while (!rep || c.r[1]) {
        f_sub<T>(c, acc, ld<T>(c, c.r[7]));
        c.r[7] += step;
        if (!rep) return;
        --c.r[1];
        if (rep == 1 ? !c.zf : c.zf) return;
    }
}
// Native body for the byte-wise table CRC64 idiom (bbrecomp, crc64_idiom): rdi = u64 state, rsi = bytes, rdx = length,
// 256 u64 entries at `table`. Leaves registers, memory (state stored after every byte, like the guest) and flags as the loop does.
// ponytail: byte-wise (latency-bound, ~8 cycles/byte); slicing-by-8 tables would be ~4x faster if it stays hot.
inline void crc64_bytes(Context& c, uint64_t table) {
    if (const uint64_t n = c.r[2]) {
        BB_WATCH_RANGE(c, c.r[7], 8);
        uint8_t* const state = host(c, c.r[7]);
        const uint8_t* const p = host(c, c.r[6]);
        const uint8_t* const t = host(c, table);
        uint64_t crc, e, i = 0, b = 0;
        std::memcpy(&crc, state, 8);
        for (uint64_t k = 0; k < n; ++k) {
            b = p[k];  // read after the previous store: the state may overlap the input
            i = (crc & 0xFF) ^ b;
            std::memcpy(&e, t + i * 8, 8);
            crc = (crc >> 8) ^ e;
            std::memcpy(state, &crc, 8);
        }
        c.r[0] = crc;
        c.r[1] = i;
        c.r[9] = b;
        c.r[8] = table;
        c.r[6] += n;
        c.r[2] = 0;
    }
    c.cf = c.of = c.sf = false;  // from `test rdx, rdx` or the final `dec rdx` (CF from the last xor)
    c.zf = c.pf = true;
}
BB_INLINE uint64_t rdtsc() { return __rdtsc(); }

// ---- Vector registers (AVX). VEX.128 writes zero bits 255:128 of the ymm register. ----
BB_INLINE __m128i xr(const Context& c, int i) { return _mm_loadu_si128(reinterpret_cast<const __m128i*>(c.ymm[i])); }
BB_INLINE void xw(Context& c, int i, __m128i v) {
    _mm_storeu_si128(reinterpret_cast<__m128i*>(c.ymm[i]), v);
    std::memset(c.ymm[i] + 16, 0, 16);
}
BB_INLINE __m128i ldx(Context& c, uint64_t a) { return _mm_loadu_si128(reinterpret_cast<const __m128i*>(host(c, a))); }
BB_INLINE void stx(Context& c, uint64_t a, __m128i v) { BB_WATCH_RANGE(c, a, 16); _mm_storeu_si128(reinterpret_cast<__m128i*>(host(c, a)), v); }
// 256-bit (VEX.256) register/memory access; callers are only emitted for ymm instructions, compiled with AVX.
BB_INLINE __m256i yr(const Context& c, int i) { return _mm256_loadu_si256(reinterpret_cast<const __m256i*>(c.ymm[i])); }
BB_INLINE void yw(Context& c, int i, __m256i v) { _mm256_storeu_si256(reinterpret_cast<__m256i*>(c.ymm[i]), v); }
BB_INLINE __m256i ldy(Context& c, uint64_t a) { return _mm256_loadu_si256(reinterpret_cast<const __m256i*>(host(c, a))); }
BB_INLINE void sty(Context& c, uint64_t a, __m256i v) { BB_WATCH_RANGE(c, a, 32); _mm256_storeu_si256(reinterpret_cast<__m256i*>(host(c, a)), v); }
BB_INLINE __m128 ps(__m128i v) { return _mm_castsi128_ps(v); }
BB_INLINE __m128i pi(__m128 v) { return _mm_castps_si128(v); }
BB_INLINE __m128d pd(__m128i v) { return _mm_castsi128_pd(v); }
BB_INLINE __m128i pi(__m128d v) { return _mm_castpd_si128(v); }
BB_INLINE __m256 ps(__m256i v) { return _mm256_castsi256_ps(v); }
BB_INLINE __m256i pi(__m256 v) { return _mm256_castps_si256(v); }
BB_INLINE __m256d pd(__m256i v) { return _mm256_castsi256_pd(v); }
BB_INLINE __m256i pi(__m256d v) { return _mm256_castpd_si256(v); }
BB_INLINE void vzeroupper(Context& c) {
    for (auto& y : c.ymm) std::memset(y + 16, 0, 16);
}
// (v)maskmovdqu: store the bytes of `data` whose mask byte has its top bit set to [rdi].
inline void maskmovdqu(Context& c, __m128i data, __m128i mask) {
    alignas(16) uint8_t d[16], m[16];
    _mm_store_si128(reinterpret_cast<__m128i*>(d), data);
    _mm_store_si128(reinterpret_cast<__m128i*>(m), mask);
    for (int i = 0; i < 16; ++i)
        if (m[i] & 0x80) st<uint8_t>(c, c.r[7] + uint64_t(i), d[i]);
}
// vfnmadd132sd: low double = -(x * y) + z (single rounding), upper lane from `rest`.
BB_INLINE __m128i fnmadd_sd(__m128i rest, __m128i x, __m128i y, __m128i z) {
    double r = std::fma(-_mm_cvtsd_f64(pd(x)), _mm_cvtsd_f64(pd(y)), _mm_cvtsd_f64(pd(z)));
    return pi(_mm_move_sd(pd(rest), _mm_set_sd(r)));
}
// (v)ucomiss / (v)comiss: ZF,PF,CF from the compare (unordered sets all three); OF=SF=0.
BB_INLINE void f_ucomiss(Context& c, __m128i a, __m128i b) {
    float x = _mm_cvtss_f32(ps(a)), y = _mm_cvtss_f32(ps(b));
    const bool un = x != x || y != y;
    c.zf = un || x == y;
    c.pf = un;
    c.cf = un || x < y;
    c.of = c.sf = false;
}
BB_INLINE void f_ucomisd(Context& c, __m128i a, __m128i b) {
    double x = _mm_cvtsd_f64(pd(a)), y = _mm_cvtsd_f64(pd(b));
    const bool un = x != x || y != y;
    c.zf = un || x == y;
    c.pf = un;
    c.cf = un || x < y;
    c.of = c.sf = false;
}

// ---- Atomics on guest memory (lock xadd / lock cmpxchg). Observed: guest code also locks operands that are not naturally aligned
// (libstdc++'s atomic_ref asserts on that); x86 handles it in hardware (split lock), so non-MSVC builds use the __atomic builtins directly. ----
#if defined(_MSC_VER)
template <typename T> using AtomicRef = std::atomic_ref<T>;
#else
template <typename T>
struct AtomicRef {
    T* p;
    explicit AtomicRef(T& r) : p(&r) {}
    T load() const { return __atomic_load_n(p, __ATOMIC_SEQ_CST); }
    T exchange(T v) const { return __atomic_exchange_n(p, v, __ATOMIC_SEQ_CST); }
    T fetch_add(T v) const { return __atomic_fetch_add(p, v, __ATOMIC_SEQ_CST); }
    bool compare_exchange_strong(T& expected, T desired) const { return __atomic_compare_exchange_n(p, &expected, desired, false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST); }
    bool compare_exchange_weak(T& expected, T desired) const { return compare_exchange_strong(expected, desired); }
};
#endif
template <typename T>
BB_INLINE AtomicRef<T> atom(Context& c, uint64_t a) {
    BB_WATCH_RANGE(c, a, sizeof(T));  // atomic accesses (xchg/cmpxchg/xadd/lock ops) may write; reported as value 0
    return AtomicRef<T>(*reinterpret_cast<T*>(host(c, a)));
}


// ---- 256-bit integer ops (AVX2 encodings): every such op works per 128-bit lane, so split into two SSE halves. ----
template <class F>
BB_INLINE __m256i ysplit(__m256i a, __m256i b, F f) {
    return _mm256_insertf128_si256(_mm256_castsi128_si256(f(_mm256_castsi256_si128(a), _mm256_castsi256_si128(b))),
                                   f(_mm256_extractf128_si256(a, 1), _mm256_extractf128_si256(b, 1)), 1);
}

// ---- MMX registers: operations run on the low qword of the SSE equivalent. ----
BB_INLINE __m128i mr(const Context& c, int i) { return _mm_cvtsi64_si128(int64_t(c.mm[i])); }
BB_INLINE void mw(Context& c, int i, __m128i v) { c.mm[i] = uint64_t(_mm_cvtsi128_si64(v)); }

// ---- x87. ponytail: registers are host doubles (53-bit mantissa instead of 64) and no tag word is kept (ffree is
// a no-op, stack over/underflow is not detected); 80-bit memory operands are unsupported. ----
BB_INLINE double& sti(Context& c, unsigned i) { return c.fpu[(c.ftop + i) & 7]; }
BB_INLINE void fpush(Context& c, double v) {
    c.ftop = uint8_t((c.ftop - 1) & 7);
    c.fpu[c.ftop] = v;
}
BB_INLINE void fpop(Context& c) { c.ftop = uint8_t((c.ftop + 1) & 7); }
template <typename T>  // float, double, or a signed integer type
BB_INLINE double ldf(Context& c, uint64_t a) {
    return double(ld<T>(c, a));
}
BB_INLINE uint16_t fstatus(const Context& c) { return uint16_t(c.fsw | (unsigned(c.ftop) << 11)); }
// fcom/fucom: C3 C2 C0 = equal / unordered / less (C1 cleared).
BB_INLINE void fcmp(Context& c, double a, double b) {
    c.fsw = uint16_t(c.fsw & ~(0x100 | 0x200 | 0x400 | 0x4000));
    if (a != a || b != b) c.fsw = uint16_t(c.fsw | 0x100 | 0x400 | 0x4000);
    else if (a < b) c.fsw = uint16_t(c.fsw | 0x100);
    else if (a == b) c.fsw = uint16_t(c.fsw | 0x4000);
}
// fcomi/fucomi: ZF,PF,CF as ucomisd; OF=SF=0.
BB_INLINE void fcomi(Context& c, double a, double b) {
    const bool un = a != a || b != b;
    c.zf = un || a == b;
    c.pf = un;
    c.cf = un || a < b;
    c.of = c.sf = false;
}
inline double fround(const Context& c, double v) {  // per FCW.RC
    switch ((c.fcw >> 10) & 3) {
    case 0: return std::nearbyint(v);
    case 1: return std::floor(v);
    case 2: return std::ceil(v);
    default: return std::trunc(v);
    }
}
template <typename T>  // already rounded; NaN/out of range stores the "integer indefinite" (most negative value)
BB_INLINE T fto_int(double r) {
    constexpr double lim = -double((std::numeric_limits<T>::min)());
    return r >= -lim && r < lim ? T(r) : (std::numeric_limits<T>::min)();
}
// fbstp: 18-digit packed BCD; NaN/out of range stores the BCD indefinite (FFFF C000 0000 0000 0000).
inline void fbstp(Context& c, uint64_t a, double v) {
    double r = fround(c, v);
    const bool neg = std::signbit(r);
    r = std::fabs(r);
    uint8_t b[10] = {};
    if (r < 1e18) {  // false for NaN
        uint64_t n = uint64_t(r);
        for (int i = 0; i < 9; ++i, n /= 100) b[i] = uint8_t((n % 10) | ((n / 10 % 10) << 4));
        b[9] = neg ? 0x80 : 0;
    } else {
        b[7] = 0xC0;
        b[8] = b[9] = 0xFF;
    }
    std::memcpy(host(c, a), b, sizeof b);
}
inline void fnstenv(Context& c, uint64_t a) {  // 32-bit protected-mode layout; only control/status/tag are meaningful
    uint8_t e[28] = {};
    const uint16_t cw = c.fcw, sw = fstatus(c), tw = 0xFFFF;  // tag word: all empty
    std::memcpy(e, &cw, 2);
    std::memcpy(e + 4, &sw, 2);
    std::memcpy(e + 8, &tw, 2);
    std::memcpy(host(c, a), e, sizeof e);
    c.fcw |= 0x3F;  // fnstenv masks all exceptions
}
inline bool ftrig_ok(Context& c, double v) {  // |v| >= 2^63: operand out of range, C2 = 1, register unchanged
    const bool ok = std::fabs(v) < 9.223372036854775808e18;
    c.fsw = uint16_t(ok ? c.fsw & ~0x400 : c.fsw | 0x400);
    return ok;
}
inline void fsin(Context& c) {
    if (ftrig_ok(c, sti(c, 0))) sti(c, 0) = std::sin(sti(c, 0));
}
inline void fcos(Context& c) {
    if (ftrig_ok(c, sti(c, 0))) sti(c, 0) = std::cos(sti(c, 0));
}
inline void fsincos(Context& c) {
    const double v = sti(c, 0);
    if (!ftrig_ok(c, v)) return;
    sti(c, 0) = std::sin(v);
    fpush(c, std::cos(v));
}
inline void fscale(Context& c) {  // st0 *= 2^trunc(st1)
    const double e = std::trunc(sti(c, 1));
    sti(c, 0) = std::ldexp(sti(c, 0), e > 100000 ? 100000 : e < -100000 ? -100000 : int(e));
}
} // namespace bb::rt
