#!/usr/bin/env python3
"""Generate src/gpu/fsr1_spv.inc: the presenter's AMD FidelityFX FSR 1 passes (EASU upscale, RCAS sharpen) as SPIR-V fragment shaders.

Input: ffx_a.h and ffx_fsr1.h of https://github.com/GPUOpen-Effects/FidelityFX-FSR (MIT), tag v1.0.2
(commit a21ffb8f6c13233ba336352bdff293894c706575), directory ffx-fsr/. Compiler: glslangValidator (Vulkan SDK).
Usage: gen_fsr1_spv.py <dir with ffx_a.h, ffx_fsr1.h> <glslangValidator> > src/gpu/fsr1_spv.inc

Interface (present.cpp): set 0 = {0: sampled image, 1: sampler}, fragment push constants (64 bytes): EASU con0..con3 (FsrEasuCon);
RCAS con0 (FsrRcasCon). Vertex shader: the presenter's full-screen triangle.
"""
import os
import subprocess
import sys
import tempfile

PRELUDE = """#version 450
#extension GL_GOOGLE_include_directive : require
#define A_GPU 1
#define A_GLSL 1
#include "ffx_a.h"
layout(set = 0, binding = 0) uniform texture2D t0;
layout(set = 0, binding = 1) uniform sampler smp;
layout(push_constant) uniform Pc { uvec4 con0, con1, con2, con3; } pc;
layout(location = 0) out vec4 out_color;
"""

# EASU of t0.
EASU = PRELUDE + """#define FSR_EASU_F 1
#include "ffx_fsr1.h"
AF4 FsrEasuRF(AF2 p) { return textureGather(sampler2D(t0, smp), p, 0); }
AF4 FsrEasuGF(AF2 p) { return textureGather(sampler2D(t0, smp), p, 1); }
AF4 FsrEasuBF(AF2 p) { return textureGather(sampler2D(t0, smp), p, 2); }
void main() {
    AF3 c;
    FsrEasuF(c, AU2(gl_FragCoord.xy), pc.con0, pc.con1, pc.con2, pc.con3);
    out_color = vec4(c, 1.0);
}
"""

# RCAS of t0 (the EASU output, same size as the target).
RCAS = PRELUDE + """#define FSR_RCAS_F 1
#include "ffx_fsr1.h"
AF4 FsrRcasLoadF(ASU2 p) { return texelFetch(sampler2D(t0, smp), p, 0); }
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}
void main() {
    AF3 c;
    FsrRcasF(c.r, c.g, c.b, AU2(gl_FragCoord.xy), pc.con0);
    out_color = vec4(c, 1.0);
}
"""


def compile_fs(src, inc, glslang):
    with tempfile.TemporaryDirectory() as d:
        fs, spv = os.path.join(d, 'pass.frag'), os.path.join(d, 'pass.spv')
        with open(fs, 'w') as f:
            f.write(src)
        subprocess.run([glslang, '-V', '--target-env', 'vulkan1.3', '-I' + inc, '-o', spv, fs], check=True, stdout=sys.stderr)
        data = open(spv, 'rb').read()
    return [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]


def main():
    inc, glslang = sys.argv[1], sys.argv[2]
    lic = [l for l in open(os.path.join(inc, 'ffx_fsr1.h')).read().split('\n')[13:29]]  # the MIT notice (lines 14-29)
    assert lic[0].startswith('// Copyright (c) 2021 Advanced Micro Devices') and lic[-1].startswith('// THE SOFTWARE.'), 'unexpected header'
    print('// Generated by tools/gen_fsr1_spv.py from AMD FidelityFX FSR 1 v1.0.2 (ffx_a.h, ffx_fsr1.h). Do not edit.')
    print('// The SPIR-V below is compiled from that code, which is under the following license:')
    print('\n'.join(lic))
    for name, src in (('kFsrEasuFs', EASU), ('kFsrRcasFs', RCAS)):
        w = compile_fs(src, inc, glslang)
        print('static const uint32_t %s[] = {' % name)
        for i in range(0, len(w), 8):
            print('    ' + ', '.join('0x%08x' % x for x in w[i:i + 8]) + ',')
        print('};')


if __name__ == '__main__':
    main()
