#!/usr/bin/env python3
"""Generate src/gpu/gcn_ops.inc (GFX7 opcode numbers -> mnemonics) from Mesa's
src/amd/compiler/aco_opcodes.py (MIT, https://gitlab.freedesktop.org/mesa/mesa).
Usage: gen_gcn_ops.py aco_opcodes.py > src/gpu/gcn_ops.inc"""
import sys
src = open(sys.argv[1]).read()
ns = {'__name__': 'aco'}
exec(compile(src, 'aco_opcodes.py', 'exec'), ns)
F = ns['Format']
fmts = ['SOP1', 'SOP2', 'SOPK', 'SOPC', 'SOPP', 'VOP1', 'VOP2', 'VOPC', 'VOP3', 'VINTRP', 'DS', 'MUBUF', 'MTBUF', 'MIMG']
print('// Generated by tools/gen_gcn_ops.py from Mesa aco_opcodes.py (MIT). GFX7 numbering. Do not edit.')
rows = []
for i in ns['instructions'].values():
    n = i.format
    base = n & 0xFFF if False else n
    for f in fmts:
        if n == getattr(F, f):
            op = i.op.gfx7
            if op >= 0:
                rows.append((f, op, i.name))
rows.sort()
for f, op, name in rows:
    print('{GcnFmt::%s, 0x%x, "%s"},' % (f, op, name))
